spring:
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/graphql
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
